//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 2020/03/06 15:21:45
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Assetz
{

    [DataContractAttribute(IsReference=true)]
    public partial class AssetDto
    {
        #region Constructors

        public AssetDto() {
        }

        public AssetDto(int id, string name, string description, int? usefulLifespan, string code, string digitalCode, System.DateTimeOffset? purchaseDate, decimal? purchasePrice, decimal salvageValue, string image, int assetTypeId, int accountId, decimal longitude, decimal latitude, AssetTypeDto assetType, AccountDto account, List<VerificationEntryDto> verificationEntries) {

          this.Id = id;
          this.Name = name;
          this.Description = description;
          this.UsefulLifespan = usefulLifespan;
          this.Code = code;
          this.DigitalCode = digitalCode;
          this.PurchaseDate = purchaseDate;
          this.PurchasePrice = purchasePrice;
          this.SalvageValue = salvageValue;
          this.Image = image;
          this.AssetTypeId = assetTypeId;
          this.AccountId = accountId;
          this.Longitude = longitude;
          this.Latitude = latitude;
          this.AssetType = assetType;
          this.Account = account;
          this.VerificationEntries = verificationEntries;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public int? UsefulLifespan { get; set; }

        [DataMember]
        public string Code { get; set; }

        [DataMember]
        public string DigitalCode { get; set; }

        [DataMember]
        public System.DateTimeOffset? PurchaseDate { get; set; }

        [DataMember]
        public decimal? PurchasePrice { get; set; }

        [DataMember]
        public decimal SalvageValue { get; set; }

        [DataMember]
        public string Image { get; set; }

        [DataMember]
        public int AssetTypeId { get; set; }

        [DataMember]
        public int AccountId { get; set; }

        [DataMember]
        public decimal Longitude { get; set; }

        [DataMember]
        public decimal Latitude { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public AssetTypeDto AssetType { get; set; }

        [DataMember]
        public AccountDto Account { get; set; }

        [DataMember]
        public List<VerificationEntryDto> VerificationEntries { get; set; }

        #endregion
    }

    [DataContractAttribute(IsReference=true)]
    public partial class AssetTypeDto
    {
        #region Constructors

        public AssetTypeDto() {
        }

        public AssetTypeDto(int id, string name, string description, string code, string image, List<AssetDto> assets) {

          this.Id = id;
          this.Name = name;
          this.Description = description;
          this.Code = code;
          this.Image = image;
          this.Assets = assets;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public string Code { get; set; }

        [DataMember]
        public string Image { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<AssetDto> Assets { get; set; }

        #endregion
    }

    [DataContractAttribute(IsReference=true)]
    public partial class VerificationEntryDto
    {
        #region Constructors

        public VerificationEntryDto() {
        }

        public VerificationEntryDto(int id, System.DateTimeOffset dateVerified, string digitalCode, string image, bool isManualVerification, int assetId, AssetDto asset) {

          this.Id = id;
          this.DateVerified = dateVerified;
          this.DigitalCode = digitalCode;
          this.Image = image;
          this.IsManualVerification = isManualVerification;
          this.AssetId = assetId;
          this.Asset = asset;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public System.DateTimeOffset DateVerified { get; set; }

        [DataMember]
        public string DigitalCode { get; set; }

        [DataMember]
        public string Image { get; set; }

        [DataMember]
        public bool IsManualVerification { get; set; }

        [DataMember]
        public int AssetId { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public AssetDto Asset { get; set; }

        #endregion
    }

    [DataContractAttribute(IsReference=true)]
    public partial class AccountDto
    {
        #region Constructors

        public AccountDto() {
        }

        public AccountDto(int id, bool isActivated, bool isOpen, System.DateTimeOffset? activationDate, string activationCode, System.DateTimeOffset? billingPlanExpiryDate, List<AssetDto> assets, List<UserDto> users) {

          this.Id = id;
          this.IsActivated = isActivated;
          this.IsOpen = isOpen;
          this.ActivationDate = activationDate;
          this.ActivationCode = activationCode;
          this.BillingPlanExpiryDate = billingPlanExpiryDate;
          this.Assets = assets;
          this.Users = users;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public bool IsActivated { get; set; }

        [DataMember]
        public bool IsOpen { get; set; }

        [DataMember]
        public System.DateTimeOffset? ActivationDate { get; set; }

        [DataMember]
        public string ActivationCode { get; set; }

        [DataMember]
        public System.DateTimeOffset? BillingPlanExpiryDate { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<AssetDto> Assets { get; set; }

        [DataMember]
        public List<UserDto> Users { get; set; }

        #endregion
    }

    [DataContractAttribute(IsReference=true)]
    public partial class UserDto
    {
        #region Constructors

        public UserDto() {
        }

        public UserDto(int id, string firstName, string lastName, string role, string email, string passwordSalt, int accountId, AccountDto account) {

          this.Id = id;
          this.FirstName = firstName;
          this.LastName = lastName;
          this.Role = role;
          this.Email = email;
          this.PasswordSalt = passwordSalt;
          this.AccountId = accountId;
          this.Account = account;
        }

        #endregion

        #region Properties

        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string FirstName { get; set; }

        [DataMember]
        public string LastName { get; set; }

        [DataMember]
        public string Role { get; set; }

        [DataMember]
        public string Email { get; set; }

        [DataMember]
        public string PasswordSalt { get; set; }

        [DataMember]
        public int AccountId { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public AccountDto Account { get; set; }

        #endregion
    }

}
