//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/03/06 15:21:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Assetz
{
    public partial class Account {

        public Account()
        {
            this.Assets = new List<Asset>();
            this.Users = new List<User>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual bool IsActivated
        {
            get;
            set;
        }

        public virtual bool IsOpen
        {
            get;
            set;
        }

        public virtual System.DateTimeOffset? ActivationDate
        {
            get;
            set;
        }

        public virtual string ActivationCode
        {
            get;
            set;
        }

        public virtual System.DateTimeOffset? BillingPlanExpiryDate
        {
            get;
            set;
        }

        public IList<Asset> Assets
        {
            get;
            set;
        }

        public IList<User> Users
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
