//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/03/06 15:21:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Assetz
{
    public partial class VerificationEntry {

        public VerificationEntry()
        {
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual System.DateTimeOffset DateVerified
        {
            get;
            set;
        }

        public virtual string DigitalCode
        {
            get;
            set;
        }

        public virtual string Image
        {
            get;
            set;
        }

        public virtual bool IsManualVerification
        {
            get;
            set;
        }

        public virtual int AssetId
        {
            get;
            set;
        }

        public Asset Asset
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
