//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/03/06 15:21:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Assetz
{
    public partial class Asset {

        public Asset()
        {
            this.VerificationEntries = new List<VerificationEntry>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual int? UsefulLifespan
        {
            get;
            set;
        }

        public virtual string Code
        {
            get;
            set;
        }

        public virtual string DigitalCode
        {
            get;
            set;
        }

        public virtual System.DateTimeOffset? PurchaseDate
        {
            get;
            set;
        }

        public virtual decimal? PurchasePrice
        {
            get;
            set;
        }

        public virtual decimal SalvageValue
        {
            get;
            set;
        }

        public virtual string Image
        {
            get;
            set;
        }

        public virtual int AssetTypeId
        {
            get;
            set;
        }

        public virtual int AccountId
        {
            get;
            set;
        }

        public virtual decimal Longitude
        {
            get;
            set;
        }

        public virtual decimal Latitude
        {
            get;
            set;
        }

        public AssetType AssetType
        {
            get;
            set;
        }

        public Account Account
        {
            get;
            set;
        }

        public IList<VerificationEntry> VerificationEntries
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
