//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 2020/03/06 15:21:45
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Assetz
{
    public partial interface IAssetTypeRepository
    {
    }
}
