//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 2020/03/06 15:21:45
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Assetz
{
    public partial interface IAssetTypeRepository : IRepository<AssetType>
    {
        ICollection<AssetType> GetAll();
        AssetType GetByKey(int _Id);
    }
}
